# Main Docker Compose configuration for Flora marketplace
# Use this with override files for different environments

services:
  postgres:
    image: postgres:15-alpine
    container_name: flora-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: flora_user
      POSTGRES_PASSWORD: flora_password
      POSTGRES_DB: flora_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U flora_user -d flora_db']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - flora-network

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: flora-backend
    restart: unless-stopped
    ports:
      - '3001:3001'
    env_file:
      - apps/backend/.env
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=postgresql://flora_user:flora_password@postgres:5432/flora_db
      - AUTH0_DOMAIN=dev-ijvur34mojpovh8e.us.auth0.com
      - AUTH0_CLIENT_ID=tegmEuc40IvXfYFDLIRnJmbsa1izkTVL
      - AUTH0_CLIENT_SECRET=your-auth0-client-secret
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - flora-network

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: flora-frontend
    restart: unless-stopped
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:3001/api
      - VITE_AUTH0_DOMAIN=dev-ijvur34mojpovh8e.us.auth0.com
      - VITE_AUTH0_CLIENT_ID=tegmEuc40IvXfYFDLIRnJmbsa1izkTVL
      - VITE_AUTH0_AUDIENCE=https://flora-api.com
    depends_on:
      - backend
    networks:
      - flora-network

volumes:
  postgres_data:
    driver: local

networks:
  flora-network:
    driver: bridge
