# Development overrides
# Run with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://flora_user:flora_password@postgres:5432/flora_db
      - AUTH0_DOMAIN=dev-ijvur34mojpovh8e.us.auth0.com
      - AUTH0_CLIENT_ID=tegmEuc40IvXfYFDLIRnJmbsa1izkTVL
      - AUTH0_CLIENT_SECRET=your-auth0-client-secret
    command: ["pnpm", "dev"]
    volumes:
      - ./apps/backend:/app/apps/backend
      - /app/apps/backend/node_modules
    working_dir: /app/apps/backend
    ports:
      - "3001:3001"

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001/api
      - VITE_AUTH0_DOMAIN=dev-ijvur34mojpovh8e.us.auth0.com
      - VITE_AUTH0_CLIENT_ID=tegmEuc40IvXfYFDLIRnJmbsa1izkTVL
    command: ["pnpm", "dev", "--host", "0.0.0.0"]
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - /app/apps/frontend/node_modules
    working_dir: /app/apps/frontend
    ports:
      - "5173:5173"

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: flora_user
      POSTGRES_PASSWORD: flora_password
      POSTGRES_DB: flora_db
    ports:
      - "5432:5432"
    command: postgres -c log_statement=all -c log_destination=stderr

  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: flora-stripe-cli
    command: listen --forward-to http://backend:3001/api/webhooks/stripe
    environment:
      - STRIPE_API_KEY=${STRIPE_SECRET_KEY}
    depends_on:
      - backend
    networks:
      - flora-network
